name: Github Actions Demo
on:
  push: 
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs: 
  Build: 
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "🎉 Whoo this job was triggered by the event: ${{ github.event.name}}"
          echo "🔥 The name of our branch is ${{github.ref}} and out repo is ."

      - uses: actions/checkout@3.3.0

      - name: List all files in our directory
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
        
